allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true
  workerd: true
minimumReleaseAgeExclude:
  - markdown-it-ts@1.1.2
  - markstream-core@2.0.8
  - markstream-vue@2.0.8
  - stream-markdown-parser@1.2.14
