import type { Context } from 'cordis'
import { Hono, type Context as HonoContext } from 'hono'
import { and, eq } from 'drizzle-orm'
import { authUserId, type ApiEnv } from './auth'
import { AttachmentCheckRequestSchema, AttachmentPurposeSchema, type AttachmentPurpose } from '@/shared/api'
import { attachments, type AttachmentRow } from '../../db/schema'
import type { DB } from '../../db/client'
import type { Assets } from '../assets'
import { parseId } from './params'
import { attachmentDisposition } from './content-disposition'

import { uploadProblem } from '@/shared/upload-policy'
import { resolveUploadPolicy } from '../upload-policy'
import { isTextMime, MAX_ATTACHMENT_BYTES, matchesFileSignature } from '@/shared/file-media'

/** Bounds images a model generates; uploaded files are bounded by the site upload policy instead. */
export const MAX_GENERATED_IMAGE_BYTES = MAX_ATTACHMENT_BYTES

type UploadCheck = (mime: string, size: number) => { status: 400 | 413 | 415; message: string } | null

/** Everything that is not a chat attachment: the fixed image rules, independent of the site policy. */
const imageUploadProblem: UploadCheck = (mime, size) => {
  if (!/^image\/(png|jpeg|webp|gif)$/.test(mime)) return { status: 415, message: 'unsupported mime' }
  if (size <= 0 || size > MAX_ATTACHMENT_BYTES) return { status: 400, message: 'bad size' }
  return null
}

/**
 * The administrator's upload policy governs chat attachments only (spec §6.2). Project icons and
 * image-studio references upload with `purpose=image` and keep the fixed image rules, so closing
 * chat uploads never breaks them.
 */
async function uploadCheck(ctx: Context, purpose: AttachmentPurpose): Promise<UploadCheck> {
  if (purpose === 'image') return imageUploadProblem
  const policy = await resolveUploadPolicy(ctx.db.orm)
  return (mime, size) => uploadProblem(policy, mime, size)
}

function hex(buf: ArrayBuffer): string {
  return [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, '0')).join('')
}

export function r2Key(userId: number, sha256: string): string {
  return `${userId}/${sha256.slice(0, 2)}/${sha256}`
}

/** Stores generated bytes as an attachment the user owns, deduplicated by digest like uploads are. */
export async function storeGeneratedAttachment(db: DB, assets: Assets, userId: number, bytes: Uint8Array, mime: string): Promise<number> {
  const digest = await crypto.subtle.digest('SHA-256', bytes as BufferSource)
  const sha256 = [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, '0')).join('')
  const [existing] = await db.select().from(attachments)
    .where(and(eq(attachments.user_id, userId), eq(attachments.sha256, sha256))).limit(1)
  if (existing) return existing.id

  const key = r2Key(userId, sha256)
  await assets.put(key, bytes, mime)
  try {
    const [row] = await db.insert(attachments).values({
      user_id: userId, sha256, mime, size: bytes.byteLength,
      width: null, height: null, r2_key: key, origin: 'generated', created_at: Date.now(),
    }).returning()
    if (!row) throw new Error('attachment insert returned no row')
    return row.id
  } catch (error) {
    // A concurrent write of the same bytes may have taken the unique index; that row owns the key.
    const [owner] = await db.select().from(attachments)
      .where(and(eq(attachments.user_id, userId), eq(attachments.sha256, sha256))).limit(1)
    if (owner) return owner.id
    throw error
  }
}

export function attachmentRoutes(ctx: Context) {
  const r = new Hono<ApiEnv>()
  const db = ctx.db.orm

  r.post('/attachments/check', async (c) => {
    const userId = authUserId(c)
    const parsed = AttachmentCheckRequestSchema.safeParse(await c.req.json())
    if (!parsed.success) return c.json({ error: 'invalid input' }, 400)
    const row = await db.query.attachments.findFirst({ where: and(eq(attachments.user_id, userId), eq(attachments.sha256, parsed.data.sha256)) })
    if (row) {
      const problem = (await uploadCheck(ctx, parsed.data.purpose))(row.mime, row.size)
      if (problem) return c.json({ error: problem.message }, problem.status)
    }
    return c.json(row ? { exists: true, attachment_id: row.id } : { exists: false })
  })

  r.put('/attachments/:sha256', async (c) => {
    const userId = authUserId(c)
    const claimed = c.req.param('sha256')
    const mime = c.req.header('content-type') ?? ''
    const purpose = AttachmentPurposeSchema.safeParse(c.req.query('purpose'))
    if (!purpose.success) return c.json({ error: 'invalid purpose' }, 400)
    const check = await uploadCheck(ctx, purpose.data)
    const declaredSize = Number(c.req.header('content-length'))
    const earlyProblem = check(mime, declaredSize > 0 ? declaredSize : 1)
    if (earlyProblem) return c.json({ error: earlyProblem.message }, earlyProblem.status)
    const bytes = await c.req.arrayBuffer()
    const problem = check(mime, bytes.byteLength)
    if (problem) return c.json({ error: problem.message }, problem.status)
    if (!matchesFileSignature(mime, new Uint8Array(bytes))) return c.json({ error: 'file content does not match mime' }, 415)
    const actual = hex(await crypto.subtle.digest('SHA-256', bytes))
    if (actual !== claimed) return c.json({ error: 'sha256 mismatch' }, 400)

    const existing = await db.query.attachments.findFirst({ where: and(eq(attachments.user_id, userId), eq(attachments.sha256, actual)) })
    if (existing) {
      const existingProblem = check(existing.mime, existing.size)
      if (existingProblem) return c.json({ error: existingProblem.message }, existingProblem.status)
      return c.json({ attachment_id: existing.id }, 201)
    }

    const key = r2Key(userId, actual)
    await ctx.assets.put(key, bytes, mime)
    const w = mime.startsWith('image/') ? Number(c.req.query('w')) || null : null
    const h = mime.startsWith('image/') ? Number(c.req.query('h')) || null : null
    const [row] = await db.insert(attachments).values({
      user_id: userId, sha256: actual, mime, size: bytes.byteLength, width: w, height: h,
      r2_key: key, origin: 'upload', created_at: Date.now(),
    }).returning()
    return c.json({ attachment_id: row!.id }, 201)
  })

  r.get('/attachments/:id', async (c) => {
    const id = parseId(c.req.param('id'))
    const row = id === null ? undefined : await db.query.attachments.findFirst({ where: and(eq(attachments.id, id), eq(attachments.user_id, authUserId(c))) })
    return serveAttachment(ctx, c, row)
  })

  return r
}

/** Answers with one attachment's bytes, or a 404 when `row` is absent. The caller decides whose rows it may look up. */
export async function serveAttachment(ctx: Context, c: HonoContext<ApiEnv>, row: AttachmentRow | undefined): Promise<Response> {
  // Successes below are cached for a year; a refusal is about who is asking and must not be.
  if (!row) return c.json({ error: 'not found' }, 404, { 'cache-control': 'no-store' })
  /**
   * Bytes are content-addressed and these rows are only ever inserted or deleted, so what an id
   * serves cannot change and revalidating settles nothing.
   *
   * `private` is the load-bearing word: the URL names no user, so a shared cache in front of this
   * Worker would answer one account's request with another account's picture. Never `public`
   * without moving an unguessable credential into the URL — and note that even then the URL
   * becomes a bearer token nobody can revoke, which is why the preview route uses short tickets.
   *
   * What remains is the browser's own store, which belongs to the browser and not to the cookie
   * currently in it. Sign-out sends `Clear-Site-Data: "cache"` for exactly that reason.
   */
  const download = c.req.query('download')
  const headers = {
    'cache-control': 'private, max-age=31536000, immutable',
    etag: `"${row.sha256}"`,
    vary: 'Cookie',
    'x-content-type-options': 'nosniff',
    // Text is shown, never run. An uploaded page served as `text/html` from this origin would run
    // its scripts as whoever opens it — an admin viewing it through the audit route included — so
    // every text type goes out as plain text, sandboxed besides. The row keeps its real type.
    ...(isTextMime(row.mime) ? { 'content-security-policy': 'sandbox' } : {}),
    // A row keeps no filename — the message part does — so a download link names the file itself.
    // `<a download>` is not enough: download managers re-request the URL and only read this header.
    ...(download ? { 'content-disposition': attachmentDisposition(download) } : {}),
  }
  const type = isTextMime(row.mime) ? 'text/plain; charset=utf-8' : row.mime
  // One row read and no object read, which is the whole point of answering it here.
  if (c.req.header('if-none-match') === headers.etag) return new Response(null, { status: 304, headers })

  // Media elements seek with `Range`, and Safari will not play audio or video without a 206.
  const range = parseByteRange(c.req.header('range'), row.size)
  if (range === null) {
    return new Response(null, { status: 416, headers: { 'cache-control': 'no-store', 'content-range': `bytes */${row.size}` } })
  }
  const stored = await ctx.assets.getStream(row.r2_key, range)
  if (!stored) return c.json({ error: 'object missing' }, 404, { 'cache-control': 'no-store' })
  if (range) {
    return new Response(stored.body, {
      status: 206,
      headers: {
        ...headers, 'accept-ranges': 'bytes', 'content-type': type, 'content-length': String(range.length),
        'content-range': `bytes ${range.offset}-${range.offset + range.length - 1}/${row.size}`,
      },
    })
  }
  return new Response(stored.body, {
    headers: { ...headers, 'accept-ranges': 'bytes', 'content-type': type, 'content-length': String(stored.size) },
  })
}

/**
 * A single `bytes=` range resolved against `size`. `undefined` means serve the whole file — no
 * header, several ranges, or a malformed one, all of which RFC 9110 lets a server ignore; `null`
 * means unsatisfiable (416).
 */
export function parseByteRange(header: string | undefined, size: number): { offset: number; length: number } | null | undefined {
  const match = header ? /^bytes=(\d*)-(\d*)$/.exec(header.trim()) : null
  if (!match || (!match[1] && !match[2])) return undefined
  if (!match[1]) {
    const suffix = Number(match[2])
    if (suffix === 0) return null
    const length = Math.min(suffix, size)
    return { offset: size - length, length }
  }
  const start = Number(match[1])
  if (start >= size) return null
  const end = match[2] ? Math.min(Number(match[2]), size - 1) : size - 1
  if (end < start) return undefined
  return { offset: start, length: end - start + 1 }
}
