import { and, eq } from 'drizzle-orm'
import type { DB } from '@/server/db/client'
import { attachments } from '@/server/db/schema'
import type { Assets } from '@/server/plugins/assets'
import { r2Key } from '@/server/plugins/api/attachments'

/** Stores generated bytes as an attachment the user owns, deduplicated by digest like uploads are. */
export async function storeGeneratedAttachment(db: DB, assets: Assets, userId: number, bytes: Uint8Array, mime: string): Promise<number> {
  const digest = await crypto.subtle.digest('SHA-256', bytes as BufferSource)
  const sha256 = [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, '0')).join('')
  const [existing] = await db.select().from(attachments)
    .where(and(eq(attachments.user_id, userId), eq(attachments.sha256, sha256))).limit(1)
  if (existing) return existing.id

  const key = r2Key(userId, sha256)
  await assets.put(key, bytes, mime)
  try {
    const [row] = await db.insert(attachments).values({
      user_id: userId, sha256, mime, size: bytes.byteLength,
      width: null, height: null, r2_key: key, origin: 'generated', created_at: Date.now(),
    }).returning()
    if (!row) throw new Error('attachment insert returned no row')
    return row.id
  } catch (error) {
    // A concurrent write of the same bytes may have taken the unique index; that row owns the key.
    const [owner] = await db.select().from(attachments)
      .where(and(eq(attachments.user_id, userId), eq(attachments.sha256, sha256))).limit(1)
    if (owner) return owner.id
    throw error
  }
}
