import { env } from 'cloudflare:workers'
import { eq } from 'drizzle-orm'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { createApp } from '@/server/app'
import { createDb } from '@/server/db/client'
import { artifactRuns, artifacts, models, providerInterfaces, providers } from '@/server/db/schema'
import { executeImageRun } from '@/server/plugins/artifacts/workflow'
import { encryptSecret } from '@/server/plugins/llm/crypto'
import { registerAndLogin } from './auth-helper'

const png = new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10])

describe('Artifact generation Workflow', () => {
  afterEach(() => vi.unstubAllGlobals())

  it('publishes generated bytes once and completes the linked Message', async () => {
    const client = await registerAndLogin({ name: 'Artist', email: 'workflow-artist@example.com', password: 'a-long-test-password' })
    const userId = Number(((await (await client.request('/api/auth/get-session')).json()) as { user: { id: string } }).user.id)
    const db = createDb(env.DB)
    const [provider] = await db.insert(providers).values({
      user_id: userId, name: 'Images', api_key: await encryptSecret(env.KEY_ENCRYPTION_SECRET, 'image-key'), created_at: 0,
    }).returning()
    const [selected] = await db.insert(providerInterfaces).values({
      provider_id: provider!.id, protocol: 'responses', base_url: 'https://images.example/v1', created_at: 0,
    }).returning()
    await db.update(providers).set({ default_interface_id: selected!.id }).where(eq(providers.id, provider!.id))
    await db.insert(models).values({
      provider_id: provider!.id, model_id: 'image-model', enabled: true, supports_image_output: true,
      metadata_resolved: { name: 'Image Model', modalities: { input: ['text'], output: ['image'] } },
    })
    const startApp = await createApp({
      env: { ...env, ARTIFACT_WORKFLOW: { create: async ({ id }: { id: string }) => ({ id, dispose() {} }) } } as unknown as Env,
      side: 'worker',
    })
    const response = await startApp.api.request('/api/artifact-runs/image', {
      method: 'POST', headers: { 'content-type': 'application/json', cookie: client.cookie }, body: JSON.stringify({
        client_request_id: crypto.randomUUID(), model: { provider_id: provider!.id, model_id: 'image-model' },
        prompt: 'A sea otter', reference_attachment_ids: [], params: { count: 1, size: { width: 1024, height: 1024 } },
      }),
    })
    expect(response.status, await response.clone().text()).toBe(202)
    const created = await response.json() as { run_id: number; conversation_id: number; message_id: number }
    let providerCalls = 0
    vi.stubGlobal('fetch', async () => {
      providerCalls++
      return Response.json({
        data: [{ b64_json: btoa(String.fromCharCode(...png)) }],
        usage: { generated_images: 1, output_tokens: 2048, total_tokens: 2048 },
      })
    })
    const workflowApp = await createApp({ env, side: 'workflow' })

    await executeImageRun(workflowApp, userId, created.run_id)
    await executeImageRun(workflowApp, userId, created.run_id)

    expect(providerCalls).toBe(1)
    expect(await db.query.artifactRuns.findFirst({ where: eq(artifactRuns.id, created.run_id) }))
      .toMatchObject({
        status: 'completed', error: null,
        usage: { generated_images: 1, output_tokens: 2048, total_tokens: 2048 },
      })
    const output = await db.query.artifacts.findFirst({ where: eq(artifacts.run_id, created.run_id) })
    expect(output).toMatchObject({ user_id: userId, output_index: 0, mime: 'image/png', width: 1024, height: 1024 })
    expect(await db.query.messages.findFirst({ where: (row, { eq }) => eq(row.id, created.message_id) }))
      .toMatchObject({ parts: [{ type: 'image', attachment_id: output!.attachment_id, artifact_id: output!.id }] })

    const runResponse = await startApp.api.request(`/api/artifact-runs/${created.run_id}`, { headers: { cookie: client.cookie } })
    expect(runResponse.status).toBe(200)
    expect(await runResponse.json()).toMatchObject({ id: created.run_id, status: 'completed', prompt: 'A sea otter' })
    const conversationsResponse = await startApp.api.request('/api/conversations?kind=image', { headers: { cookie: client.cookie } })
    expect(await conversationsResponse.json()).toMatchObject([{ id: expect.any(Number), kind: 'image', title: 'A sea otter' }])
    const runsResponse = await startApp.api.request(`/api/artifact-runs?conversation_id=${created.conversation_id}`, { headers: { cookie: client.cookie } })
    expect(await runsResponse.json()).toMatchObject([{ id: created.run_id, status: 'completed' }])
    const galleryResponse = await startApp.api.request('/api/artifacts?kind=image', { headers: { cookie: client.cookie } })
    expect(galleryResponse.status).toBe(200)
    expect(await galleryResponse.json()).toMatchObject({
      artifacts: [{ id: output!.id, run_id: created.run_id, prompt: 'A sea otter', model_name: 'Image Model' }],
      next_cursor: null,
    })
    const conversationGallery = await startApp.api.request(`/api/artifacts?kind=image&conversation_id=${created.conversation_id}`, { headers: { cookie: client.cookie } })
    expect(await conversationGallery.json()).toMatchObject({ artifacts: [{ id: output!.id }] })
    const runGallery = await startApp.api.request(`/api/artifacts?kind=image&run_id=${created.run_id}`, { headers: { cookie: client.cookie } })
    expect(await runGallery.json()).toMatchObject({ artifacts: [{ id: output!.id }] })
    const otherRunGallery = await startApp.api.request(`/api/artifacts?kind=image&run_id=${created.run_id + 1}`, { headers: { cookie: client.cookie } })
    expect(await otherRunGallery.json()).toEqual({ artifacts: [], next_cursor: null })
    const content = await startApp.api.request(`/api/artifacts/${output!.id}/content`, { headers: { cookie: client.cookie } })
    expect(content.status).toBe(200)
    expect(new Uint8Array(await content.arrayBuffer())).toEqual(png)
  })

  it('sends the model extra body under the run override, read when the run executes', async () => {
    const client = await registerAndLogin({ name: 'Extra', email: 'workflow-extra@example.com', password: 'a-long-test-password' })
    const userId = Number(((await (await client.request('/api/auth/get-session')).json()) as { user: { id: string } }).user.id)
    const db = createDb(env.DB)
    const [provider] = await db.insert(providers).values({
      user_id: userId, name: 'Images', api_key: await encryptSecret(env.KEY_ENCRYPTION_SECRET, 'image-key'), created_at: 0,
    }).returning()
    const [selected] = await db.insert(providerInterfaces).values({
      provider_id: provider!.id, protocol: 'chat-completions', base_url: 'https://images.example/v1', created_at: 0,
    }).returning()
    await db.update(providers).set({ default_interface_id: selected!.id }).where(eq(providers.id, provider!.id))
    const [model] = await db.insert(models).values({
      provider_id: provider!.id, model_id: 'seedream', enabled: true, supports_image_output: true,
      metadata_resolved: { name: 'Seedream', modalities: { input: ['text'], output: ['image'] } },
      image_extra_body: { watermark: true, seed: 1 },
    }).returning()
    const startApp = await createApp({
      env: { ...env, ARTIFACT_WORKFLOW: { create: async ({ id }: { id: string }) => ({ id, dispose() {} }) } } as unknown as Env,
      side: 'worker',
    })
    const response = await startApp.api.request('/api/artifact-runs/image', {
      method: 'POST', headers: { 'content-type': 'application/json', cookie: client.cookie }, body: JSON.stringify({
        client_request_id: crypto.randomUUID(), model: { provider_id: provider!.id, model_id: 'seedream' },
        prompt: 'A sea otter', reference_attachment_ids: [], params: { count: 1, extra: { seed: 2 } },
      }),
    })
    expect(response.status, await response.clone().text()).toBe(202)
    const created = await response.json() as { run_id: number }
    // Edited after the run was queued: the run must pick this up, not a copy taken at creation.
    await db.update(models).set({ image_extra_body: { watermark: false, seed: 1 } }).where(eq(models.id, model!.id))
    let body: unknown
    vi.stubGlobal('fetch', async (input: RequestInfo | URL, init?: RequestInit) => {
      body = await new Request(input, init).json()
      return Response.json({ data: [{ b64_json: btoa(String.fromCharCode(...png)) }] })
    })

    await executeImageRun(await createApp({ env, side: 'workflow' }), userId, created.run_id)

    expect(body).toMatchObject({ model: 'seedream', watermark: false, seed: 2 })
  })
})
