/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/settings': RouteRecordInfo<
      '/admin/settings',
      '/admin/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chats/': RouteRecordInfo<
      '/chats/',
      '/chats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/images': RouteRecordInfo<
      '/images',
      '/images',
      Record<never, never>,
      Record<never, never>,
      | '/images/'
      | '/images/a/[artifactId]'
      | '/images/new'
      | '/images/s/[conversationId]'
      | '/images/s/[conversationId]/a/[artifactId]'
    >,
    '/images/': RouteRecordInfo<
      '/images/',
      '/images',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/images/a/[artifactId]': RouteRecordInfo<
      '/images/a/[artifactId]',
      '/images/a/:artifactId',
      { artifactId: ParamValue<true> },
      { artifactId: ParamValue<false> },
      | never
    >,
    '/images/new': RouteRecordInfo<
      '/images/new',
      '/images/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/images/s/[conversationId]': RouteRecordInfo<
      '/images/s/[conversationId]',
      '/images/s/:conversationId',
      { conversationId: ParamValue<true> },
      { conversationId: ParamValue<false> },
      | '/images/s/[conversationId]/a/[artifactId]'
    >,
    '/images/s/[conversationId]/a/[artifactId]': RouteRecordInfo<
      '/images/s/[conversationId]/a/[artifactId]',
      '/images/s/:conversationId/a/:artifactId',
      { artifactId: ParamValue<true>, conversationId: ParamValue<true> },
      { artifactId: ParamValue<false>, conversationId: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/new': RouteRecordInfo<
      '/new',
      '/new/:conversationId?',
      { conversationId?: ParamValueZeroOrOne<true> },
      { conversationId?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/project/[projectId]': RouteRecordInfo<
      '/project/[projectId]',
      '/project/:projectId',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | '/project/[projectId]/'
      | '/project/[projectId]/new'
      | '/project/[projectId]/settings'
    >,
    '/project/[projectId]/': RouteRecordInfo<
      '/project/[projectId]/',
      '/project/:projectId',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    '/project/[projectId]/new': RouteRecordInfo<
      '/project/[projectId]/new',
      '/project/:projectId/new/:conversationId?',
      { conversationId?: ParamValueZeroOrOne<true>, projectId: ParamValue<true> },
      { conversationId?: ParamValueZeroOrOne<false>, projectId: ParamValue<false> },
      | never
    >,
    '/project/[projectId]/settings': RouteRecordInfo<
      '/project/[projectId]/settings',
      '/project/:projectId/settings',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account': RouteRecordInfo<
      '/settings/account',
      '/settings/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/appearance': RouteRecordInfo<
      '/settings/appearance',
      '/settings/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/images': RouteRecordInfo<
      '/settings/images',
      '/settings/images',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/plugins/': RouteRecordInfo<
      '/settings/plugins/',
      '/settings/plugins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/plugins/[pluginId]/': RouteRecordInfo<
      '/settings/plugins/[pluginId]/',
      '/settings/plugins/:pluginId',
      { pluginId: ParamValue<true> },
      { pluginId: ParamValue<false> },
      | never
    >,
    '/settings/plugins/[pluginId]/data': RouteRecordInfo<
      '/settings/plugins/[pluginId]/data',
      '/settings/plugins/:pluginId/data',
      { pluginId: ParamValue<true> },
      { pluginId: ParamValue<false> },
      | never
    >,
    '/settings/providers/': RouteRecordInfo<
      '/settings/providers/',
      '/settings/providers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/[id]': RouteRecordInfo<
      '/settings/providers/[id]',
      '/settings/providers/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/client/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/admin/settings.vue': {
      routes:
        | '/admin/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/chats/index.vue': {
      routes:
        | '/chats/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/images.vue': {
      routes:
        | '/images'
        | '/images/'
        | '/images/a/[artifactId]'
        | '/images/new'
        | '/images/s/[conversationId]'
        | '/images/s/[conversationId]/a/[artifactId]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/client/pages/images/index.vue': {
      routes:
        | '/images/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/images/a/[artifactId].vue': {
      routes:
        | '/images/a/[artifactId]'
      views:
        | never
      pathParamNames:
        | 'artifactId'
    }
    'src/client/pages/images/new.vue': {
      routes:
        | '/images/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/images/s/[conversationId].vue': {
      routes:
        | '/images/s/[conversationId]'
        | '/images/s/[conversationId]/a/[artifactId]'
      views:
        | 'default'
      pathParamNames:
        | 'conversationId'
    }
    'src/client/pages/images/s/[conversationId]/a/[artifactId].vue': {
      routes:
        | '/images/s/[conversationId]/a/[artifactId]'
      views:
        | never
      pathParamNames:
        | 'artifactId'
    }
    'src/client/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/new.vue': {
      routes:
        | '/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/project/[projectId].vue': {
      routes:
        | '/project/[projectId]'
        | '/project/[projectId]/'
        | '/project/[projectId]/new'
        | '/project/[projectId]/settings'
      views:
        | 'default'
      pathParamNames:
        | 'projectId'
    }
    'src/client/pages/project/[projectId]/index.vue': {
      routes:
        | '/project/[projectId]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/project/[projectId]/new.vue': {
      routes:
        | '/project/[projectId]/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/project/[projectId]/settings.vue': {
      routes:
        | '/project/[projectId]/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/projects/index.vue': {
      routes:
        | '/projects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/settings/account.vue': {
      routes:
        | '/settings/account'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/settings/appearance.vue': {
      routes:
        | '/settings/appearance'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/settings/images.vue': {
      routes:
        | '/settings/images'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/settings/plugins/index.vue': {
      routes:
        | '/settings/plugins/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/settings/plugins/[pluginId]/index.vue': {
      routes:
        | '/settings/plugins/[pluginId]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/settings/plugins/[pluginId]/data.vue': {
      routes:
        | '/settings/plugins/[pluginId]/data'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/settings/providers/index.vue': {
      routes:
        | '/settings/providers/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/settings/providers/[id].vue': {
      routes:
        | '/settings/providers/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
