/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/c/[sessionId]': RouteRecordInfo<
      '/c/[sessionId]',
      '/c/:sessionId',
      { sessionId: ParamValue<true> },
      { sessionId: ParamValue<false> },
      | never
    >,
    '/chats/': RouteRecordInfo<
      '/chats/',
      '/chats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/[projectId]': RouteRecordInfo<
      '/projects/[projectId]',
      '/projects/:projectId',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/appearance': RouteRecordInfo<
      '/settings/appearance',
      '/settings/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/plugins': RouteRecordInfo<
      '/settings/plugins',
      '/settings/plugins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/projects/[id]': RouteRecordInfo<
      '/settings/projects/[id]',
      '/settings/projects/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/settings/providers/': RouteRecordInfo<
      '/settings/providers/',
      '/settings/providers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers/[id]': RouteRecordInfo<
      '/settings/providers/[id]',
      '/settings/providers/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/client/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/c/[sessionId].vue': {
      routes:
        | '/c/[sessionId]'
      views:
        | never
      pathParamNames:
        | 'sessionId'
    }
    'src/client/pages/chats/index.vue': {
      routes:
        | '/chats/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/projects/index.vue': {
      routes:
        | '/projects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/projects/[projectId].vue': {
      routes:
        | '/projects/[projectId]'
      views:
        | never
      pathParamNames:
        | 'projectId'
    }
    'src/client/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/settings/appearance.vue': {
      routes:
        | '/settings/appearance'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/settings/plugins.vue': {
      routes:
        | '/settings/plugins'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/settings/projects/[id].vue': {
      routes:
        | '/settings/projects/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/client/pages/settings/providers/index.vue': {
      routes:
        | '/settings/providers/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/client/pages/settings/providers/[id].vue': {
      routes:
        | '/settings/providers/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
